let obj = {
	// idNo_back: '法人/股东身份证人像面',
	// idNo_front: '法人/股东身份证国徽面',
	idNo_front: '法人/股东身份证人像面',
	idNo_back: '法人/股东身份证国徽面',
	liveness_image: '刷脸视频',
	articles_association: '公司章程',
	board_resolution: '董事会决议',
	loan_agreement: '借款协议',
	loan_contract: '业务合同',
	loan_invoice: '业务发票',
	loan_buy_contract: '不动产购买合同',
	hiring_paperwork: '招标文书',
	letter_acceptance: '中标通知书',
	open_account_addr: '地址信息',
	business_license: '营业执照',
	legal_idNo_back: '法人身份证人像面',
	legal_idNo_front: '法人身份证国徽面',
	shareholder_idNo_back: '控股25%以上的股东身份证人像面',
	shareholder_idNo_front: '控股25%以上的股东身份证国徽面',
	shareholder_legal_idNo_back: '法人身份证人像面',
	shareholder_legal_idNo_front: '法人身份证国徽面',
	market_record: '地址信息',
	survey_trade: '贸易信息',
	survey_order_addr: '地址信息',
	survey_running_account: '银行流水证明材料',
	survey_tax_invoice: '税务数据证明材料',
	survey_pledge: '抵质押证明材料',
	survey_risk: '其他风险证明材料',
	survey_upload: '调查上传信息',
	open_account_video: '视频',
	voice_frequency: '音频',
	pledge_materials: '抵押品权属资料/抵押品权属资料',
	originals_contract: '合同正本',
	loan_authorization:'借款授权书',
	loan_common_check_addr:	'地址信息',
	comp_info: '企业基本信息补充资料',
	liquit_assets: '流动资金贷款监控补充资料',
	fixed_assets: '固定资产贷款监控补充资料',
	account_statement_info: '他行银行流水余额补充资料',
	tax_invoice_info: '税务发票信息补充资料',
	trade_info: '贸易行业补充信息',
	finance_info: '财务信息'

}
export default obj